[package]
name = "filesync"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
fs_extra = "1.3.0"
retrotv-file = "0.0.3-alpha"

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
predicates = "3"
